firstname = input("enter the first name")
lastname = input("enter your last name")
city = input("enter the city")
print ("your last name and first name:",firstname +""+ lastname)
print("your city name:",city)
